name: Precheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-dist:
    name: Check `dist` folder
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm start
      - run: git diff --exit-code
